[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "yams-robot-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dynamixel-sdk>=3.8.4",
    "lerobot>=0.4.1",
    "i2rt",
    "ipykernel>=7.1.0",
    "pyyaml>=6.0",
]

[tool.uv.sources]
i2rt = { path = "third_party/i2rt", editable = true }

[dependency-groups]
dev = [
    "opencv-python>=4.12.0.88",
]
